### PR TITLE
Fix base-url rel-path not added to images within contents

### LINKED ISSUE #9: Issue with :base-url that has a context path
When you're serving assets from a CDN, you can add a `:base-url` to each asset. This URL will be added to links to the assets. Like this:

``` cl
{:path "/scripts/code.js"
 :base-url "http://cdn.example.com"}
```

When you call `(optimus.link/file-path request "/scripts/code.js")` you get `http://cdn.example.com/scripts/code.js`.

The problem arises in CSS files. They too link to assets, but unless you explicitly update their `:contents`, they won't use the `:base-url`. This isn't a problem in the example above. Since they're using absolute URLs, they'll use the base URL as long as they're served from there.

However, if the base URL contains a context path: `http://cdn.example.com/mysite` - then the absolute paths in CSS fail.

In that case, we either need to update the contents of all CSS files with the base URL. Or we could use relative paths instead.

### PR DESCRIPTION
**Pull request by lsnape**
Fixes #9

### CODE REVIEW

**Comment by magnars** [comment]
Hi! Thanks for the fix. This looks like an okay solution to the problem. 

Would you mind making a separate test for this feature, with some explanation in line with the other tests?

Also, the function `new-path` could use a name that better pinpoints what it is doing.

**Comment by lsnape** [comment]
I've made the changes you requested. Let me know if you think anything else is required :)

**Comment by magnars** [comment]
This looks great, thank you!

**Comment by magnars** [comment]
`0.19.2` released with this fix.

**Comment by lsnape** [comment]
My pleasure :) and thanks for making a release 👍

**Pull request merged**
