### PR TITLE
Replace shell script with cross platform makefile

### PR DESCRIPTION
**Pull request by augustl**
The shell script build-js-sources.sh does not run on Windows.

Instead of creating a build-js-sources.cmd, the shell script is
rewritten to a makefile that works on both Windows and *nix.

Tested on both Windows 10 and Ubuntu 18.04.

### CODE REVIEW

**Comment by magnars** [comment]
Excellent idea. Seems like the build is breaking tho. You checking it out?

**Comment by augustl** [comment]
Will do!

**Comment by augustl** [comment]
@magnars fixed! Just forgot the `mkdir` step for the resources folder :)

**Comment by magnars** [comment]
Looking good! :)

**Pull request merged**
