### PR TITLE
Attempt to fix autorefresh strategy #42

### PR DESCRIPTION
**Pull request by env0der**
Not sure if it will work on JDK 1.6. Let's see what Travis will say.

### CODE REVIEW

**Comment by env0der** [comment]
Ok, Travis says that everything is fine. 

I would also like to test it locally with may app, but I don't know how to install the library to the local Maven repository and then use it in a project. @magnars, how do you do it?

**Comment by magnars** [comment]
Yeah, the tests are running fine - but remember that we couldn't get the
actual integration test to work? So it's just a mock.

To install it to your .m2, run

lein install

on the command line. I usually change the version in project.clj to
something else first, to avoid it overwriting an official version.
søn. 16. aug. 2015 kl. 23.56 skrev Anton Onyshchenko <
notifications@github.com>:

**Comment by magnars** [comment]
This looks like just a revert of my refactoring, right? That does not work - I tried it already.

**Comment by env0der** [comment]
Ah, I did not realise that, sorry. I will try again in the evening today.
```lein install``` for some reason did not work on my system - the new lib version was not found by my app.

**Pull request closed without merging**
