### PR TITLE
Use JSR223 to execute JS optimizations w/ GraalJS, Nashorn or Rhino

### PR DESCRIPTION
**Pull request by radhikalism**
### Summary

Picking up where #52 left off, but with some twists:

- Drop clj-v8 entirely [1]
- Prefer GraalJS by default (opt-out) [2]
- Compatible with Nashorn (opt-in, where available for now) [3]
- Compatible with Rhino (opt-in, where provided and selected) [4]
- Compatible with conceivably any future JSR223 JS engine loaded by end-users and selected using `environ`

Unlike past experience in #52 it seems like all tests now pass (including the dodgy multiple selector test with clean-css), at least so far with a recent JDK (v11).

The PR is open for review but obviously incomplete. What do you think of this approach at a high level?

### How to try it

* Checkout
* `lein midje` to execute tests with the default JS engine (GraalJS)
* `lein with-profile +rhino midje` to execute tests with Rhino
* `lein with-profile +nashorn midje` to execute tests with Nashorn extremely slowly (on a suitably old JDK)

The choice of JS engine is given through `environ`, so it can be passed like this too:

`OPTIMUS_JS_ENGINES=nashorn lein midje` (so long as the engine dependency is also on the classpath)

The `environ` ergonomics is how Optimus users can override the choice of JS engine, alongside declaring necessary engine dependencies and/or exclusions.

### Notes

[1] clj-v8 is super outdated and the release situation is questionable. I investigated [eclipsesource/j2v8](https://github.com/eclipsesource/J2V8/) as an alternative, but they are pivoting to Android-only. If someone makes a fresh v8 JSR223 binding for Java, it may be worth testing against too.

[2] Meanwhile GraalJS looks pretty complete, maintained and performs very reasonably, so it could be a fine default.

[3] Nashorn is deprecated and spits a warning when used in recent JDKs, it may soon be removed entirely.

[4] Rhino doesn't have a JSR223 interface upstream but there is a [third-party adapter](https://bitbucket.org/bunkenburg/rhino-js-engine) that seems adequate.

### CODE REVIEW

**Comment by magnars** [comment]
Outstanding! This looks like just what is needed. Thank you for doing this
work. What would you say remains to be done?

man. 14. okt. 2019 kl. 20:47 skrev Radhika Reddy <notifications@github.com>:

**Comment by radhikalism** [comment]
> What would you say remains to be done?

Not much, at least:

* Docs updates
* Unit tests for `optimus.js` (which was in a separate project, so I'll just copy over the tests)
* Reconsider error handling strategy (try portable exception instead of return value)
* Minor code cleanups

**Comment by magnars** [comment]
I have now read through all the code, and everything looks good to me. Well done indeed. Let's do a release candidate for this change, and I will start using it in my projects to give it a thorough spin.

**Comment by magnars** [comment]
Can we get rid of this warning somehow?
```
lein midje
Warning: implicit hook found: lein-environ.plugin/hooks
Hooks are deprecated and will be removed in a future version.
nil
All checks (1950) succeeded.
```

**Comment by magnars** [comment]
I'm not sure if this is something we can fix?

```
lein with-profile +nashorn midje
Warning: implicit hook found: lein-environ.plugin/hooks
Hooks are deprecated and will be removed in a future version.

FAIL It correctly minifies several rules for the same selector at (minify_test.clj:151)
Expected:
"div,table{border:0}table{margin:0}"
Actual:
"div,table{border:0}"
Diffs: strings have 1 difference (55% similarity)
                expected: "...der:0}(table{margin:0})"
                actual:   "...der:0}(---------------)"
nil
FAILURE: 1 check failed.  (But 1949 succeeded.)
```

**Comment by magnars** [comment]
I have pushed `[optimus "1.0.0-rc1"]` to clojars. Let's give it a spin. @augustl could you give this a spin on windows? :)

**Comment by radhikalism** [comment]
> Can we get rid of this warning somehow?
> 
> ```
> lein midje
> Warning: implicit hook found: lein-environ.plugin/hooks
> Hooks are deprecated and will be removed in a future version.

It looks like this issue is open upstream at weavejester/environ/issues/88 and will have to be fixed there before Leiningen 3.0 removes hooks altogether.

> I'm not sure if this is something we can fix?
> This is with JDK8. The same does not happen on JDK11. I think we'll let this slide.

Yes, I thought it would be low priority too, considering Nashorn will be removed from JDKs eventually. But I have a todo task to look at polyfilling `Array.splice` to see if it can be fixed trivially (as it was in #52 — but this time the polyfill will need to be applied conditionally).

**Comment by radhikalism** [comment]
> FAIL It correctly minifies several rules for the same selector at (minify_test.clj:151)
> Expected:
> "div,table{border:0}table{margin:0}"
> Actual:
> "div,table{border:0}"
> Diffs: strings have 1 difference (55% similarity)
>                 expected: "...der:0}(table{margin:0})"
>                 actual:   "...der:0}(---------------)"
> nil
> FAILURE: 1 check failed.  (But 1949 succeeded.)
> ```
> 
> This is with JDK8. The same does not happen on JDK11. I think we'll let this slide.

Added a commit fixing this by patching `Array.splice` conditionally — only when Nashorn is instantiated on Java 8.

**Comment by magnars** [comment]
Excellent 👌

lør. 19. okt. 2019 kl. 15:37 skrev radhika reddy <notifications@github.com>:

**Comment by augustl** [comment]
> @augustl could you give this a spin on windows? :)

Got this warning when starting it up:

```
...
Retrieving com/ibm/icu/icu4j/62.1/icu4j-62.1.jar from central
Retrieving org/graalvm/js/js-scriptengine/19.2.0.1/js-scriptengine-19.2.0.1.jar from central
Retrieving net/java/dev/jna/jna/3.2.2/jna-3.2.2.jar from central
Retrieving optimus/optimus/1.0.0-rc1/optimus-1.0.0-rc1.jar from clojars
Warning: clj-v8-native 0.1.4 will still have its native content in :native-path
  Consider doing `lein clean` to remove potentially stale native files
```

Did a `lein clean`, did not try starting up without it.

But 🥁 🥁 🥁  everything works fine on Win10 🎉 🎉 🎉 🎉 🎉 

Or, the app starts up fine and some of the web pages I tested works just fine. Will report back with any oddities if there are any.

**Comment by magnars** [comment]
@augustl That's great to hear! 👏 I can confirm that the warning goes away after a clean. It's just residue from the old clj-v8.

**Comment by magnars** [comment]
I am planning on working on Optimus all day Thursday in 6 days, mainly focused on merging this and porting the other Optimus packages. Any experiences from testing this I should know about, @radhikalism ?

**Comment by radhikalism** [comment]
> I am planning on working on Optimus all day Thursday in 6 days, mainly focused on merging this and porting the other Optimus packages. Any experiences from testing this I should know about, @radhikalism ?

Nothing to report. It would be good if anyone else has tested the RCs with varying configurations and especially combining optimus-* asset loaders etc. My (current) use case is almost trivial (vanilla Optimus) and it's a new site so regressions are harder to spot.

**Comment by kendagriff** [comment]
Thanks for all this hard work.

Question: Is there any way for the 0.20.2 code to not rely on clj-v8? On the new Apple M1, the following throws an error on launch:

```
(defn- find-file-path-fragments
   []
   (let [os-name (System/getProperty "os.name")
         os-arch (System/getProperty "os.arch")]
     (case [os-name os-arch]
       ["Mac OS X" "x86_64"] ["macosx/x86_64/" ".dylib"]
       ["Linux" "x86_64"]    ["linux/x86_64/" ".so"]
       ["Linux" "amd64"]     ["linux/x86_64/" ".so"]
       ["Linux" "x86"]       ["linux/x86/" ".so"]
       ["Linux" "i386"]      ["linux/x86/" ".so"]
       ["Linux" "i486"]      ["linux/x86/" ".so"]
       ["Linux" "i586"]      ["linux/x86/" ".so"]
       ["Linux" "i686"]      ["linux/x86/" ".so"]
       (throw (Exception. (str "Unsupported OS/archetype: " os-name " " os-arch))))))
```

Even if we use an alternate JS engine, clj-v8 is still being required, and throwing the error. Any suggestions?

**Comment by magnars** [comment]
It seems like I have a "work in progress" to remove the clj-v8 dependency that I haven't looked at since the end 2019. 😬 I currently have no idea why I didn't finish that work. I'll see if I can figure out what is going on.

**Comment by kendagriff** [comment]
Thank you thank you! In the meantime, I'm testing RC3 to see if it works.

**Comment by kendagriff** [comment]
FYI: RC3 fixed this issue with the Apple M1. We've been testing it in our staging environment successfully so far; we'll let you know if we see anything weird.

**Comment by magnars** [comment]
Excellent, thank you!

tor. 11. mar. 2021 kl. 19:49 skrev Kendall Buchanan <
***@***.***>:

**Comment by augustl** [comment]
IIRC the reason RC3 isn't released is that it requires a lot of plugins to Optimus to also be updated? Since they call directly into clj-v8 stuff in optimus core.

**Comment by magnars** [comment]
Aha, yes, excellent recollection. That’s why! Thanks. :-)

tor. 11. mar. 2021 kl. 20:33 skrev August Lilleaas ***@***.***
>:

> IIRC the reason RC3 isn't released is that it requires a lot of plugins to
> Optimus to also be updated? Since they call directly into clj-v8 stuff in
> optimus core.
>

**Comment by kendagriff** [comment]
In other words, inasmuch as we're not using Optimus plugins, we're free and clear of clj-v8?

**Comment by magnars** [comment]
Sounds about right.

tor. 11. mar. 2021 kl. 20:47 skrev Kendall Buchanan <
***@***.***>:

**Pull request merged**
